# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:4.4.12
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  app-demo-with-mongo:
    image: 'demo-app-with-mongo:latest'
    build:
      context: .
    container_name: app-demo-with-mongo
    depends_on:
      - mongo
    environment:
      - TZ=Europe/Rome
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=INFO
      - SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE=admin
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/admin
    ports:
      - "8082:8082"